### ISSUE TITLE
any plan for 3.0?

### ISSUE THREAD

**Issue by wjh000123** [bsm/openrtb#56]
Hi there,

since openrtb 3.0 is out for a while, is there any plan for it?

thanks!

**Comment by dim** [comment]
@wjh000123 there is no immediate plan, no, but we have been incorporating new features from the later 2.x versions when these were requested: https://github.com/bsm/openrtb/pulls?q=is%3Apr+is%3Aclosed. If you are looking for a particular 3.0 feature, please let us know. Otherwise, a PR would really be much appreciated.
