### ISSUE TITLE
Version to use bsm/openrtb | openRTB specification 

### ISSUE THREAD

**Issue by shivakumarss** [bsm/openrtb#75]
I have been using this api for quiet a long time, i have forked this binaries in my repo ( reason for doing it was to customise a little ) 

- Now i am planning to re-write my apis with go modules using the latest 1.4.11 of go.
- I see there has been a change in `bsm/openrtb v3.0.2` for instance earlier i was consuming impression object as request.Imp[] and now its been changed to request.Impressions[].
- After migrating my go code to mod, it shows `github.com/bsm/openrtb v2.1.2+incompatible`

I have 2 questions wrt to versions : 

- Can i use the the latest version of `bsm/openrtb v3.0.2` and include in go.mod as `github.com/bsm/openrtb/v3 v3.0.2` for consumption of openRTB 2.2 - 2.5 requests or do i need to downgrade from v3.0.2 to 2.x version of `bsm/openrtb` ?
- Another question i have is, `bsm/openrtb v3.0.2`supports openRTB spec 3.x requests ? 

Thanks a lot.

**Comment by dim** [comment]
Hi,

First of all, I think you need to import it consistently as `"github.com/bsm/openrtb/v3" - https://blog.golang.org/v2-go-modules. 

This library doesn't try to be in line with any particular version of OpenRTB. The spec is 100% backwards compatible and since there are no collisions, we are not afraid to mix features from different spec versions as long as those are "final" and not just "draft". 

Hope that makes sense.
